# Generated by Django 5.1.4 on 2024-12-25 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='食物名稱')),
                ('expiration_date', models.DateField(verbose_name='到期時間')),
            ],
            options={
                'verbose_name': '食物',
                'verbose_name_plural': '食物清單',
                'ordering': ['expiration_date'],
            },
        ),
    ]
