# Generated by Django 5.1.4 on 2024-12-25 07:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notify', '0002_food_notified_expired_food_notified_expiring'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Food',
            new_name='FoodItem',
        ),
    ]
